"""Initializing Migration

Revision ID: 640790c4ee5b
Revises: 
Create Date: 2023-01-15 22:22:55.754737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640790c4ee5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_app')
    op.add_column('up_to_date_news', sa.Column('newsText', sa.String(length=200000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('up_to_date_news', 'newsText')
    op.create_table('news_app',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('newsTitle', sa.VARCHAR(length=200), nullable=False),
    sa.Column('newsUrl', sa.VARCHAR(length=200), nullable=False),
    sa.Column('newsImage', sa.TEXT(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('newsImage')
    )
    # ### end Alembic commands ###
